<% APP_NAME = 'schools' %>
<% DATABASE_TYPE='mysql2'%>

common: &common
 adapter: <%= DATABASE_TYPE %>
 encoding: utf8
 reconnect: false
 pool: 5
 username: rails 
 password: 

development:
 <<: *common
 database: <%= APP_NAME + '_' + 'development' %>

test:
 <<: *common
 database: <%= APP_NAME + '_' + 'test' %>

production:
 <<: *common
 database: <%= APP_NAME + '_' + 'production' %>
